package com.company.Transaction;

public enum TransactionType {
    PAYMENT,
    WITHDRAWAL,
    CLOSEDEPOSIT,
    OPENDEPOSIT,
    CLOSELOAN,
    OPENLOAN,
    CLOSEACCOUNT,
    OPENACCOUNT,
    INTERESTRATECALCULATION,
    REPORT,
    DEPOSE,
    CHANGEOFINTERESTRATE,
    RECEIVE,
    INTERBANKPAYMENT,
    INTERBANKINCOME,
    DEBIT,
    FAILURE,
    ADDCARD,
    REMOVECARD,
    USECARD,
    TAKELOAN
}
