package com.company.Transaction;

public enum TransactionType {
    PAYMENT,
    WITHDRAWAL,
    CLOSEDEPOSIT,
    OPENDEPOSIT,
    CLOSELOAN,
    OPENLOAN,
    CLOSEACCOUNT,
    OPENACCOUNT,
    INTERESTRATECALCULATION,
    REPORT,
    DEPOSE,
    CHANGEOFINTERESTRATE,
    RECEIVE,
    INTERBANK,
    DEBIT
}
